accuracy: true
batch_size: 2
class_groups:
- - 0
  - 1
- - 2
  - 3
- - 4
  - 5
- - 6
  - 7
- - 8
  - 9
data_root: /mnt/dataset/
dataset_name: AWA
dataset_type: std
device: cuda
model_name: basic_conv
model_path: /mnt/checkpoints/AWA/std/basic_conv_std/AWA_basic_conv
num_batches_per_file: 1
num_classes: 10
num_files: 1
save_dir: /mnt/outputs/
start_file: 0
validation_size: 2000
xai_method: influence
