accuracy: true
batch_size: 32
class_groups:
- - 0
  - 1
- - 2
  - 3
- - 4
  - 5
- - 6
  - 7
- - 8
  - 9
data_root: <data_root>
dataset_name: MNIST
dataset_type: mark
device: cuda
model_name: basic_conv
model_path: <project_root>/checkpoints/MNIST/mark/basic_conv_mark/MNIST_basic_conv
num_batches_per_file: 100
num_classes: 10
num_files: 500
save_dir: <project_root>/explanations/MNIST/mark/basic_conv_mark/similarity
start_file: 0
validation_size: 2000
xai_method: similarity
