accuracy: true
batch_size: 32
class_groups:
- - 0
  - 1
- - 2
  - 3
- - 4
  - 5
- - 6
  - 7
- - 8
  - 9
data_root: <data_root>
dataset_name: MNIST
dataset_type: group
device: cuda
model_name: basic_conv
model_path: <project_root>/checkpoints/MNIST/group/basic_conv_group/MNIST_basic_conv
num_batches_per_file: 100
num_classes: 5
num_files: 500
save_dir: <project_root>/explanations/MNIST/group/basic_conv_group/representer
start_file: 0
validation_size: 2000
xai_method: representer
