accuracy: true
batch_size: 32
class_groups:
- - 0
  - 1
- - 2
  - 3
- - 4
  - 5
- - 6
  - 7
- - 8
  - 9
data_root: <data_root>
dataset_name: CIFAR
dataset_type: group
device: cuda
model_name: resnet
model_path: <project_root>/checkpoints/CIFAR/group/resnet_group/CIFAR_resnet
num_batches_per_file: 100
num_classes: 5
num_files: 500
save_dir: <project_root>/explanations/CIFAR/group/resnet_group/similarity
start_file: 0
validation_size: 2000
xai_method: similarity
